#!/bin/bash
gunicorn="gunicorn"
prog="app"
prog_nossl="app-no-ssl"
PROJECT_HOME="/root/clickmd"
pid="/var/lock/$prog"
pid_nossl="/var/lock/$prog_nossl"
LOGFILE="/root/clickmd/log/gunicorn.log"
LOGFILE_nossl="/root/clickmd/log/gunicorn-no-ssl.log"
KEYS="/root/clickmd/keys"
PORT=443
PORT_nossl=80
RETVAL=0
start() {
    echo -n $"Starting $prog:"
    cd $PROJECT_HOME
    $gunicorn --timeout 600 --log-file=$LOGFILE --certfile=$KEYS/clickmd.crt --keyfile=$KEYS/clickmd.key --ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS --ssl-version 5 --daemon -w 4 -b 0.0.0.0:$PORT --pid=$pid $prog:app
    $gunicorn --timeout 600 --log-file=$LOGFILE_nossl --daemon -w 1 -b 0.0.0.0:$PORT_nossl --pid=$pid_nossl $prog_nossl:app
    RETVAL=$?
    cd -
    echo
    [ $RETVAL -eq 0 ] && touch $pid
    return $RETVAL
}
stop() {
    echo -n $"Killing all unicorn sessions... "
    kill -KILL $(ps aux | grep '[g]unicorn' | awk '{print $2}')
    sleep 5
}
reload() {
    echo -n $"Reloading $prog:"
    kill -HUP `cat $pid`
    RETVAL=$?
    echo
    echo -n $"Reloading $prog_nossl:"
    kill -HUP `cat $pid_nossl`
    RETVAL=$?
    echo
    return $RETVAL
}
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    reload)
        reload
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        RETVAL=1
        ;;
esac
exit $RETVAL
